defaults:
  - machine: aws
  - model: default
  - dataset: default
  - loss: default
  - train_params: default
  - distributed: default
  - _self_

output_dir: ${hydra:run.dir}
root_data_dir: ${machine.root_data_dir}
mapanything_dataset_metadata_dir: ${machine.mapanything_dataset_metadata_dir}
root_pretrained_checkpoints_dir: ${machine.root_pretrained_checkpoints_dir}
root_experiments_dir: ${machine.root_experiments_dir}
root_uniception_pretrained_checkpoints_dir: ${machine.root_uniception_pretrained_checkpoints_dir}
