# String for model factory
model_str: "must3r"
# Model config
model_config:
  name: "must3r"
  # Checkpoint path
  ckpt_path: "${root_pretrained_checkpoints_dir}/MUSt3R_512.pth"
  # Retrieval Checkpoint path
  retrieval_ckpt_path: "${root_pretrained_checkpoints_dir}/MUSt3R_512_retrieval_trainingfree.pth"
# Image Normalization Type
data_norm_type: "dust3r"
# MASt3R checkpoint is already loaded in the inference wrapper
pretrained: null
# Torch hub force reload
torch_hub_force_reload: false
