# String for model factory
model_str: "vggt"
# Model config
model_config:
  name: "vggt"
  # Load pre-trained weights
  load_pretrained_weights: true
  # Load custom checkpoint
  load_custom_ckpt: true
  # Custom checkpoint path
  custom_ckpt_path: "${root_pretrained_checkpoints_dir}/vggt_1B_commercial.pt"
# Image Normalization Type
data_norm_type: "identity"
# VGGT checkpoint is already loaded in the inference wrapper
pretrained: null
# Torch hub force reload
torch_hub_force_reload: false
