defaults:
  - default

# Number of views parameter for the multi-view datasets
num_views: 1

# Test Resolution
resolution_test_eth3d: ${dataset.resolution_options.518_many_ar}
resolution_test_scannetpp: ${dataset.resolution_options.518_many_ar}
resolution_test_tav2_wb: ${dataset.resolution_options.518_many_ar}

# Test Set
# Sample 20 frames from each scene
# ETH3D: 13 scenes
# ScanNet++V2: 30 scenes
# TartanAirV2-WB: 5 scenes
test_dataset:
  "+ 260 @ ${dataset.eth3d_wai.test.dataset_str}
  + 600 @ ${dataset.scannetpp_wai.test.dataset_str}
  + 100 @ ${dataset.tav2_wb_wai.test.dataset_str}"
