# Ray Directions on Unit Sphere + Depth along Ray + Global Camera Pose (Trans + Quats) + Confidence + Mask
input_dim: 6
scene_rep_dim: 4
type: "raydirs+depth+pose+confidence+mask"
scene_rep_type: "raydirs+depth+pose"
dense_pred_init_dict:
  name: "raydirs+depth+pose+confidence+mask"
  ray_directions_mode: "linear"
  ray_directions_normalize_to_unit_sphere: true
  ray_directions_normalize_to_unit_image_plane: false
  ray_directions_vmin: ${special_float:"-inf"}
  ray_directions_vmax: ${special_float:"inf"}
  ray_directions_clamp_min_of_z_dir: false
  ray_directions_z_dir_min: ${special_float:"-inf"}
  depth_mode: "exp"
  depth_vmin: 0
  depth_vmax: ${special_float:"inf"}
  confidence_type: "exp"
  confidence_vmin: 1
  confidence_vmax: ${special_float:"inf"}
pose_pred_init_dict:
  name: "raydirs+depth+pose+confidence+mask"
  cam_trans_mode: "linear"
  cam_trans_vmin: ${special_float:"-inf"}
  cam_trans_vmax: ${special_float:"inf"}
  quaternions_mode: "linear"
  quaternions_normalize: true
  quaternions_vmin: ${special_float:"-inf"}
  quaternions_vmax: ${special_float:"inf"}
