# String for model factory
model_str: "anycalib"
# Model config
model_config:
  name: "anycalib"
# Image Normalization Type
data_norm_type: "identity"
# AnyCalib checkpoint is already loaded in the inference wrapper
pretrained: null
# Torch hub force reload
torch_hub_force_reload: false
