defaults:
  - default
  - encoder: dinov2_large
  - info_sharing: aat_ifr_24_layers
  - pred_head: dpt_pose
  - task: images_only

# String for model factory
model_str: "mapanything_ablations"
# Model config
model_config:
  name: "mapanything_ablations"
  encoder_config: ${model.encoder}
  info_sharing_config: ${model.info_sharing}
  pred_head_config: ${model.pred_head}
  geometric_input_config: ${model.task}
# Image Normalization Type
data_norm_type: ${model.encoder.data_norm_type}
