defaults:
  - default

# Optimizer parameters specific to submodules
submodule_configs:
  # Encoder
  encoder:
    lr: 5e-06
    min_lr: 5e-08
    warmup_epochs: ${train_params.warmup_epochs}
    weight_decay: ${train_params.weight_decay}
    schedule_type: ${train_params.schedule_type}
