# @package _global_

defaults:
  - override /data: depth

name: monodepth

pi3:
  pretrained_model_name_or_path: yyfz233/Pi3
  # pretrained_model_name_or_path: checkpoints/Pi3

eval_datasets:
  - sintel
  - bonn
  - kitti
  - nyu-v2

invariant: median-scale  # using median(gt) / median(pred) as scale factor

overwrite: False
no_crop: True
load_img_size: 512

device: cuda

verbose: False
save_suffix: null