# @package _global_

defaults:
  - override /data: relpose-angular

name: relpose-angular

pi3:
  pretrained_model_name_or_path: yyfz233/Pi3
  # pretrained_model_name_or_path: checkpoints/Pi3

eval_datasets:
  - Re10K
  - CO3Dv2

no_crop: False
load_img_size: 512

device: cuda

verbose: False

seed: 42

save_suffix: null
