# @package _global_

defaults:
  - override /data: depth

name: videodepth

pi3:
  pretrained_model_name_or_path: yyfz233/Pi3
  # pretrained_model_name_or_path: checkpoints/Pi3

eval_datasets:
  - sintel
  - bonn
  - kitti

# align: scale
align: scale&shift

overwrite: False
no_crop: True
load_img_size: 512

device: cuda

verbose: False
save_suffix: null