root: # needs to be set via argument: root=<wai_dataset_root_path>

model_path: /fsx/xrtech/checkpoints/MoGe/moge-2-vitl-normal/model.pt
model_name: moge2
out_path: moge/v0
device: cuda
random_scene_processing_order: true

scene_filters:
  - exists: images
  - exists: scene_meta.json
  - process_state_not: [moge, finished]

# dataloader configs
batch_size: 8
prefetch_factor: 6
num_workers: 6

resize: 1600 # the maximum long-size resizing length 
# inference speed / results. check 'moge infer --help'
resolution_level: 9

overwrite: true

frame_modalities: # what to load for each frame
  - image