stage: # set stage via CLI
root:  # path of wai-formatted dataset

gpus: 0
cpus: 10
mem: 20
scenes_per_job: 20
conda_env: # pass the name of our conda environment
nodelist:

stages:
  conversion:
    script: conversion/scannetppv2.py
    config: conversion/scannetppv2.yaml
    scenes_per_job: 100 # fast
  undistortion:
    script: undistort.py
    config: undistortion/scannetppv2.yaml
  covisibility:
    script: covisibility.py
    config: covisibility/covisibility_gt_depth.yaml
    gpus: 1
  moge:
    script: run_moge.py
    config: moge/default.yaml
    gpus: 1
