stage: # set stage via CLI
root: # path of wai-formatted dataset

gpus: 0
cpus: 10
mem: 20
scenes_per_job: 1  # Only 9 scenes --> 9 jobs
conda_env: # pass the name of our conda environment
nodelist:

stages:
  conversion:
    script: conversion/unrealstereo4k.py
    config: conversion/unrealstereo4k.yaml
    scenes_per_job: 1
  covisibility:
    script: covisibility.py
    config: covisibility/covisibility_gt_depth.yaml
    gpus: 1
