sapiens:
  use_torchscript: true
  fp16: False
  input_crop_size_hw: (1440, 1080)
  mean: [123.5, 116.5, 103.5]
  std: [58.5, 57.0, 57.5]
  compile_model: False
  batch_size: 32

vggt:
  use_torchscript: null
  fp16: False
  input_crop_size_hw: (1440, 1080)
  mean: [123.5, 116.5, 103.5]
  std: [58.5, 57.0, 57.5]
  compile_model: False
  batch_size: 32

pi3:
  use_torchscript: null
  fp16: False
  input_crop_size_hw: (1440, 1080)
  mean: [123.5, 116.5, 103.5]
  std: [58.5, 57.0, 57.5]
  compile_model: False
  batch_size: 32
