stage: # set stage via CLI
root: # path of wai-formatted dataset

gpus: 0
cpus: 10
mem: 20
scenes_per_job: 200
conda_env: # pass the name of our conda environment
nodelist:

stages:
  conversion:
    script: conversion/dl3dv.py
    config: conversion/dl3dv.yaml
    scenes_per_job: 100 # fast
  undistortion:
    script: undistort.py
    config: undistortion/default.yaml
  moge:
    script: run_moge.py
    config: moge/default.yaml
    gpus: 1
  mvsanywhere:
    script: run_mvsanywhere.py
    config: mvs_anywhere/default.yaml
    gpus: 1
  covisibility:
    script: covisibility.py
    config: covisibility/covisibility_pred_depth_mvsa.yaml
    gpus: 1
  depth_consistency_confidence:
    script: depth_consistency_confidence.py
    config: depth_consistency_confidence/depth_consistency_confidence_mvsa.yaml
    gpus: 1
