defaults:
  - machine: aws
  - model: default
  - dataset: default
  - _self_

output_dir: ${hydra:run.dir}
root_data_dir: ${machine.root_data_dir}
mapanything_dataset_metadata_dir: ${machine.mapanything_dataset_metadata_dir}
root_pretrained_checkpoints_dir: ${machine.root_pretrained_checkpoints_dir}
root_experiments_dir: ${machine.root_experiments_dir}
root_uniception_pretrained_checkpoints_dir: ${machine.root_uniception_pretrained_checkpoints_dir}

### Benchmarking args
seed: 0
# Disable CUDNN Benchmark (Disable for variable resolution & number of view training)
disable_cudnn_benchmark: true
# Batch size for inference (Metrics are computed per multi-view set and averaged, not per batch of multi-view sets)
batch_size: 20
# Use mixed precision for inference
amp: 1
# Floating point type to use for mixed precision
amp_dtype: "bf16"
