# Root directory containing all datasets
root_data_dir: ???
# Dataset metadata directory
mapanything_dataset_metadata_dir: ???
# Root directory containing pretrained checkpoints for custom models
root_pretrained_checkpoints_dir: ???
# Root directory to log experiments
root_experiments_dir: ???
# Root directory containing UniCeption pretrained checkpoints
root_uniception_pretrained_checkpoints_dir: ???
# Root directory containing external benchmark data
external_benchmark_data_root_data_dir: ???
